spring.config.import=optional:file:./env.properties
spring.application.name=ScoreBTW API
#Porta del server
server.port=3001
#Configurazione del Database
spring.datasource.url=jdbc:postgresql://localhost:5432/scorebtw_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
#Configurazione JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#Configurazione JWT
jwt.secret=${JWT_SECRET}
#Configurazione Cloudinary
cloudinary.name=${CLOUDINARY_NAME}
cloudinary.key=${CLOUDINARY_KEY}
cloudinary.secret=${CLOUDINARY_SECRET}
#Configurazione Mailgun
mailgun.api.key=${MAILGUN_API}
mailgun.domain=${MAILGUN_DOMAIN}
mailgun.from.address=${MAILGUN_ADDRESS}
rawg.api.key=${RAWG_API_KEY}
rawg.api.url=https://api.rawg.io/api